name: 'clang-format'
description: 'Format C/++ code using clang-format'
author: 'wispacerace'
inputs: 
  exclude:
    description: 'directories to exclude, space-separated'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
